name: Testing workflow variables

on:
  workflow_dispatch:

env:
   cloud: google-cloud

jobs:
  greeting_job:
     runs-on: ubuntu-latest
     evn: 
       Greeting: Hello
     steps: 
       - name: "Say Hello Venkatesh it's monday"
        run: echo "@Geetings $First_Name is using $cloud!"
        env: 
          First_Name: Vishnu
       
